Allow Address 2 to be empty
shadimanna/dhl-logistic-services-for-woocommerce pull request #121
Opened 2022-08-23 10:01 UTC by Abdalsalaam

https://wordpress.org/support/topic/shipping-address-2-is-empty-error-message-2

2022-08-23 10:16 UTC, iyut requested changes
So sorry for being picky here. Basically, just need to change some spacing.

2022-08-23 10:16 UTC, iyut commented on pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
> +					if( $set_key == 0 ) {
```suggestion
					if ( 0 === $set_key ) {
```

2022-08-23 10:16 UTC, iyut commented on pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
> +					if( $set_key === false ) {
```suggestion
					if ( false === $set_key ) {
```

2022-08-23 10:16 UTC, iyut commented on pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
> +						if (is_numeric($address_value)) {
```suggestion
						if ( is_numeric( $address_value ) ) {
```

2022-08-23 10:16 UTC, iyut commented on pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
> +					foreach ($address_exploded as $address_key => $address_value) {
```suggestion
					foreach ( $address_exploded as $address_key => $address_value ) {
```

2022-08-23 10:16 UTC, iyut commented on pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
> +                    if( count($address_exploded) == 1 && 'DE' === $args['shipping_address']['country'] ) {
```suggestion
                    if ( 1=== count( $address_exploded ) && 'DE' === $args['shipping_address']['country'] ) {
```

2022-08-23 10:16 UTC, iyut commented on pr-dhl-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-soap-label.php
> +				if( count($address_exploded) > 1 ) {
```suggestion
				if ( count( $address_exploded ) > 1 ) {
```

2022-08-29 11:09 UTC, Abdalsalaam commented
> So sorry for being picky here. Basically, just need to change some spacing.

thank you! I prefer these review

2022-08-30 04:50 UTC, iyut approved these changes
LGTM!

2022-09-01 13:20 UTC, closed without merging