Fix WC old versions compatibility
shadimanna/dhl-logistic-services-for-woocommerce pull request #197
Opened 2023-07-07 15:21 UTC by Abdalsalaam

### Description
https://wordpress.org/support/topic/fatal-error-since-update-3-4-6/

2023-07-10 05:02 UTC, iyut requested changes
Hi @Abdalsalaam , I made some comments on this PR

2023-07-10 07:51 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
>  		global $post;
@iyut order parameter will be passed only if HPOS enabled, isn't it ?

2023-07-12 01:50 UTC, iyut commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
>  		global $post;
based on [this line](https://github.com/WordPress/WordPress/blob/d097367dbbbf1d0ffc584202b80e9136bd324a0e/wp-admin/includes/class-wp-posts-list-table.php#L1387), it's actually post ID.

2023-07-12 02:01 UTC, iyut commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
>  		global $post;
and for HPOS, we will need to use this action : `add_action( 'manage_woocommerce_page_wc-orders_custom_column', array( $this, 'add_order_label_column_header' ), 1, 2 );`

2023-07-12 02:03 UTC, iyut commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
>  		global $post;
This is the snippet that I use for checking the order instance : 

```
add_action( 'manage_shop_order_posts_custom_column', array( $this, 'example_of_custom_column' ), 1, 2 );
add_action( 'manage_woocommerce_page_wc-orders_custom_column', array( $this, 'example_of_custom_column' ), 1, 2 );
public function example_of_custom_column( $column, $post_id_or_order ) {
		$order = ( $post_id_or_order instanceof WC_Order ) ? $post_id_or_order : wc_get_order( $post_id_or_order );

		if ( ! ( $order instanceof WC_Order ) ) {
			return;
		}
...
...
...
}
```

Hope this make sense.

2023-07-18 08:49 UTC, iyut approved these changes
The changes LGTM!

2023-07-19 07:25 UTC, merged