Update old checkout field to new woocommerce checkout block - preferr…
shadimanna/dhl-logistic-services-for-woocommerce pull request #244
Opened 2024-10-08 07:57 UTC by sal4sup

Update old checkout field to new woocommerce checkout block - preferred services

2025-02-25 08:33 UTC, Abdalsalaam commented
I'm getting these warnings when activating the plugin :
```php
Warning: Undefined array key "dhl_display_packstation" in /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-extend-block-core.php on line 54

Warning: Undefined array key "dhl_display_post_office" in /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-extend-block-core.php on line 62

Warning: Undefined array key "dhl_display_packstation" in /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-blocks-integration.php on line 255

Warning: Undefined array key "dhl_display_parcelshop" in /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-blocks-integration.php on line 256

Warning: Undefined array key "dhl_display_post_office" in /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-blocks-integration.php on line 257

Warning: Cannot modify header information - headers already sent by (output started at /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-extend-block-core.php:54) in /home/progressus/public_html/wp-admin/includes/misc.php on line 1438

Warning: Cannot modify header information - headers already sent by (output started at /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-extend-block-core.php:54) in /home/progressus/public_html/wp-includes/functions.php on line 7137

Warning: Cannot modify header information - headers already sent by (output started at /home/progressus/public_html/wp-content/plugins/dhl-for-woocommerce/includes/class-pr-dhl-extend-block-core.php:54) in /home/progressus/public_html/wp-admin/admin-header.php on line 9
```

2025-02-25 08:55 UTC, Abdalsalaam commented
I noticed that when the store is using , checkout blocks fields added, this should be added only for Paket ( Germany based stores )
![image](https://github.com/user-attachments/assets/3d17512a-6081-4235-813d-7148656dbbce)

2025-02-25 09:11 UTC, Abdalsalaam commented
It seems Post Number field have a default value : `{dhl_postnum}`
<img width="911" alt="image" src="https://github.com/user-attachments/assets/97cf4ab3-8306-434d-8308-4804cd33ba28" />


===
When selecting "Regular Address" type, DHL packstations/branches fields should be hidden
<img width="937" alt="image" src="https://github.com/user-attachments/assets/58558a48-25db-4835-9e36-9e2c89d36324" />


=====
DHL Preferred Delivery is always **empty**
<img width="614" alt="image" src="https://github.com/user-attachments/assets/5c440ddc-ce8e-4ace-b946-feba0efcab47" />

2025-02-25 09:14 UTC, Abdalsalaam requested changes

2025-02-25 21:48 UTC, sal4sup commented
> It seems Post Number field have a default value : `{dhl_postnum}` <img alt="image" width="911" src="https://private-user-images.githubusercontent.com/19236737/416597880-97cf4ab3-8306-434d-8308-4804cd33ba28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA1MTUxNjMsIm5iZiI6MTc0MDUxNDg2MywicGF0aCI6Ii8xOTIzNjczNy80MTY1OTc4ODAtOTdjZjRhYjMtODMwNi00MzRkLTgzMDgtNDgwNGNkMzNiYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI1VDIwMjEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOWZkODNkMmY2NjE4ZGUzODkwZTZiYzllM2FmZjhmMTg4OTFkNDA0MjVkOWUxYWVmNzAxNDE2ZWQ5MDQxMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w-4SWIUu6Jf6behN_PnmZXZI55C-fZWmsdlBrr_WgfU">
> 
> === When selecting "Regular Address" type, DHL packstations/branches fields should be hidden <img alt="image" width="937" src="https://private-user-images.githubusercontent.com/19236737/416599901-58558a48-25db-4835-9e36-9e2c89d36324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA1MTUxNjMsIm5iZiI6MTc0MDUxNDg2MywicGF0aCI6Ii8xOTIzNjczNy80MTY1OTk5MDEtNTg1NThhNDgtMjVkYi00ODM1LTllMzYtOWUyYzg5ZDM2MzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI1VDIwMjEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Y2Y0ZWJlYzY4OGEyZGQ5NmQ5Y2I4MzUxNGExYzE3MTBmOWZjOTNlN2UzOWIyMDVjYjg0NTk4NWQyM2JmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Abi8ii63BL6tUtqUs9j0yNAP7COhGLK6ugpAHhVx6A0">
> 
> ===== DHL Preferred Delivery is always **empty** <img alt="image" width="614" src="https://private-user-images.githubusercontent.com/19236737/416604131-5c440ddc-ce8e-4ace-b946-feba0efcab47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA1MTUxNjMsIm5iZiI6MTc0MDUxNDg2MywicGF0aCI6Ii8xOTIzNjczNy80MTY2MDQxMzEtNWM0NDBkZGMtY2U4ZS00YWNlLWI5NDYtZmViYTBlZmNhYjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI1VDIwMjEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjAxMWE3NWVjOTU2ZThiZDdhM2E4MDA2ODgzM2M1OGMzMWYyOTc3MzY5ZTYwMGIzZmI4NTRkODI4NGIzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dugWfiqaOfVhLABbl818eVjP8lHD4mw5PAVgw-FNV2o">

All issues are resolved. Regarding {dhl_postnum}, it's related to set_format_post_number in class-pr-dhl-front-end-paket.php

2025-03-10 04:18 UTC, iyut commented on pr-dhl-woocommerce/includes/class-pr-dhl-blocks-integration.php
> +			'google_maps_enabled' => $dhl_settings['dhl_display_google_maps'],
I got this error when testing this PR : `PHP Warning:  Undefined array key "dhl_display_google_maps" in /var/www/html/wp-content/plugins/pr-dhl-woocommerce/includes/class-pr-dhl-blocks-integration.php on line 268
`

2025-04-23 06:03 UTC, Abdalsalaam approved these changes

2025-04-23 06:10 UTC, merged