Product editor compatibility
shadimanna/dhl-logistic-services-for-woocommerce pull request #246
Opened 2024-10-15 13:47 UTC by OlfatProgressus

2025-01-27 12:13 UTC, Abdalsalaam requested changes

2025-01-27 12:13 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-product-paket-editor.php
> +class PR_DHL_WC_Product_Paket_Editor {
I think its better to create an abstract class, for product editor and moving the compatibility declaration to it.

```suggestion
class PR_DHL_WC_Product_Editor_Paket extends PR_DHL_WC_Product_Editor {
```

2025-01-27 12:13 UTC, Abdalsalaam commented on pr-dhl-woocommerce/pr-dhl-woocommerce.php
> +		}
No need for duplicating this code, you can just add it to `get_pr_dhl_wc_product` function

2025-01-31 00:15 UTC, sal4sup commented on pr-dhl-woocommerce/pr-dhl-woocommerce.php
> +			include_once PR_DHL_PLUGIN_DIR_PATH . 'includes/abstract-pr-dhl-wc-product-editor.php';
```suggestion
			/include_once PR_DHL_PLUGIN_DIR_PATH . 'includes/abstract-pr-dhl-wc-product-editor.php';
```

2025-01-31 00:15 UTC, sal4sup commented on pr-dhl-woocommerce/pr-dhl-woocommerce.php
> +			include_once PR_DHL_PLUGIN_DIR_PATH . 'includes/abstract-pr-dhl-wc-product-editor.php';
```suggestion
			/include_once PR_DHL_PLUGIN_DIR_PATH . 'includes/abstract-pr-dhl-wc-product-editor.php';
```

2025-01-31 00:17 UTC, sal4sup commented on pr-dhl-woocommerce/pr-dhl-woocommerce.php
> +			include_once PR_DHL_PLUGIN_DIR_PATH . 'includes/abstract-pr-dhl-wc-product-editor.php';
Warning: include_once(\wp-content\plugins\pr-dhl-woocommerceincludes/abstract-pr-dhl-wc-product-editor.php): Failed to open stream: No such file or directory in \wp-content\plugins\pr-dhl-woocommerce\pr-dhl-woocommerce.php on line 197

Warning: include_once(): Failed opening \wp-content\plugins\pr-dhl-woocommerceincludes/abstract-pr-dhl-wc-product-editor.php' for inclusion (include_path='C:\xampp\php\PEAR') in \wp-content\plugins\pr-dhl-woocommerce\pr-dhl-woocommerce.php on line 197

2025-02-03 15:54 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-product-editor-deutsche-post.php
> +			);
@OlfatProgressus 
Can we move this to the abstract since its used in both DP and Packet ? ( Check how its done in `abstract-pr-dhl-wc-product.php` )

2025-02-04 08:55 UTC, OlfatProgressus commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-product-editor-deutsche-post.php
> +			);
Done

2025-02-12 08:36 UTC, Abdalsalaam approved these changes
LGTM, I pushed some changes for adding doc for functions and params

2025-02-12 08:39 UTC, merged