Fix vulnerabilities
shadimanna/dhl-logistic-services-for-woocommerce pull request #248
Opened 2024-11-01 08:33 UTC by OlfatProgressus

2024-11-04 15:22 UTC, Abdalsalaam commented on pr-dhl-woocommerce/assets/css/jquery.fancybox.min.css
Is there any reason for adding these files? 

pr-dhl-woocommerce/assets/css/jquery.fancybox.min.css
pr-dhl-woocommerce/assets/img/icon.svg
pr-dhl-woocommerce/assets/js/jquery.fancybox.min.js

2024-11-04 15:54 UTC, OlfatProgressus commented on pr-dhl-woocommerce/assets/css/jquery.fancybox.min.css
@Abdalsalaam  PCP plugin error when include external links

2024-11-05 02:07 UTC, Abdalsalaam requested changes

2024-11-05 02:07 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-deutsche-post.php
> +			<?php echo implode( '', wp_kses_post( $table_rows ) ); ?>
This change caused Fatal error
<img width="538" alt="image" src="https://github.com/user-attachments/assets/1130340e-c58d-4665-9993-84c2e0980d45">

$table_rows is array of HTML table rows , and no need to use **wp_kses_post** here

@OlfatProgressus

2024-11-05 02:07 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/abstract-pr-dhl-wc-order.php
> +				'print_button' => wp_kses_post( $print_button ),
these are 3 buttons created within the code, not the user, and the label/text for these buttons are already escaped so there is no need to use **wp_kses_post**

2024-11-05 02:13 UTC, Abdalsalaam requested changes

2024-11-05 02:13 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-deutsche-post.php
> +		echo wp_kses_post( $this->dhl_order_meta_box_table() );
```suggestion
		echo $this->dhl_order_meta_box_table();
```

We should not sanitize HTML content that is made by the plugin itself
<img width="705" alt="image" src="https://github.com/user-attachments/assets/99153064-d733-4a16-abd7-4f544e4fc074">

2024-11-05 02:26 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/REST_API/Parcel_DE/Client.php
> +				esc_html( $message )
![Uploading image.png…]()

2024-11-06 09:27 UTC, Abdalsalaam approved these changes
I pushed some changes and fixes then I tested Paket and Deutsche Post functionalities, all looks good
thank you

2024-11-06 09:28 UTC, merged