fix warnings
shadimanna/dhl-logistic-services-for-woocommerce pull request #252
Opened 2024-11-06 18:25 UTC by OlfatProgressus

2025-01-26 01:48 UTC, Abdalsalaam requested changes
`$dhl_label_items` is not defined, can you check what `$args['dhl_settings']['participation']` used for?

2025-03-11 07:45 UTC, OlfatProgressus commented
@Abdalsalaam $args['dhl_settings']['participation'] is used [here](https://github.com/shadimanna/dhl-logistic-services-for-woocommerce/blob/0fb6d75216d5a9ceb10619403b842e6c2d2a9802/pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php#L1126) to compose $args['dhl_pickup_billing_number']

2025-03-20 10:59 UTC, Abdalsalaam requested changes

2025-03-20 10:59 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-wizard-paket.php
> -											esc_html__( 'Please configure your access to the DHL Paket APIs by means of authentication. Your username for the DHL business customer portal is required. Please note the lowercase letter
what is the reason of this change?

2025-03-20 10:59 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
> +			$args['dhl_settings']['participation']   = ! empty( $dhl_label_items ) ? $this->shipping_dhl_settings[ 'dhl_participation_' . $dhl_label_items['pr_dhl_product'] ] : '';
<img width="399" alt="image" src="https://github.com/user-attachments/assets/8ffac906-d5a6-4739-a5ba-fcdd373b18f7" />
`$dhl_label_items` **is undefined**

2025-03-20 11:22 UTC, OlfatProgressus commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-wizard-paket.php
> -											esc_html__( 'Please configure your access to the DHL Paket APIs by means of authentication. Your username for the DHL business customer portal is required. Please note the lowercase letter
<a href="%s" target="_blank">here</a> appeared as a text not html

2025-04-22 11:10 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-wizard-paket.php
> -											esc_html__( 'Please configure your access to the DHL Paket APIs by means of authentication. Your username for the DHL business customer portal is required. Please note the lowercase letter
@OlfatProgressus alright, we can do something like : 
```php
printf(
											/* translators: %s: link to DHL business portal */
											esc_html__( 'Please configure your access to the DHL Paket APIs by means of authentication. Your username for the DHL business customer portal is required. Please note the lowercase letters and test your access data in advance at %1$shere%2$s.', 'dhl-for-woocommerce' ),
											'<a href="' . PR_DHL_PAKET_BUSSINESS_PORTAL . '" target="_blank">',
                                            '</a>'
										);
```

2025-05-08 18:30 UTC, Abdalsalaam commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
> -
I'm not getting what is done here?

2025-05-09 07:29 UTC, OlfatProgressus commented on pr-dhl-woocommerce/includes/class-pr-dhl-wc-order-paket.php
> -
It's just a code reorder, I reverted this change

2025-05-26 08:44 UTC, merged